const basePath = "/images/blog-page/blog-post-images/";

export const blogPosts = [
  // {
  //   title: "",
  //   post_date: "",
  //   image_src: "/images/blog-page/blog-post-images/2026//-a.webp",
  //   image_alt: "",
  //   image_width: 456,
  //   image_height: 342,
  //   second_image_src: "/images/blog-page/blog-post-images/2026//-b.webp",
  //   second_image_width: 456,
  //   second_image_height: 342,
  //   second_image_alt: "",
  //   text: [
  //     "",
  //     "",
  //     "",
  //     "",
  //     "",
  //     "",
  //   ],
  //   // video: {
  //   //   playback_id: "",
  //   //   title: "",
  //   //   image_src: "",
  //   // },
  //   closing_tag: "Until next time,",
  //   author: "",
  //   slug: "",
  //   description: "",
  // },
  {
    title: "Constructing the Future",
    post_date: "August 2026",
    image_src: "/images/blog-page/blog-post-images/2026/august/aug-a.webp",
    image_alt: "Dump trucks, excavators, and cranes at an active construction site.",
    image_width: 456,
    image_height: 342,
    second_image_src: "/images/blog-page/blog-post-images/2026/august/aug-b.webp",
    second_image_width: 456,
    second_image_height: 342,
    second_image_alt: "A baseball game viewed from the stands, with the field and scoreboard in view.",
    text: [
      "I am very fortunate to be working at a company that celebrates its staff and their accomplishments. This month we were able to help a huge company celebrate their staff victories and successful projects.",
      "Construction requires many experts to collaborate on all of the facets of building. An experienced and knowledgeable team means everything. We were able to highlight projects from Wisconsin to Colorado that were shining examples of what can be accomplished with the right team.",
      "I keep learning about so many industries and organizations that I'm not sure I would have ever known if I didn't work at MMM. I'm really valuing every opportunity to learn and support our great team.",
    ],
    // video: {
    //   playback_id: "",
    //   title: "",
    //   image_src: "",
    // },
    closing_tag: "If you ever even want to talk through a video project, call me!",
    author: "Clark Martin",
    slug: "constructing-the-future-august-2026",
    description: "MMM highlights construction projects from Wisconsin to Colorado, celebrating staff accomplishments and the value of an experienced, knowledgeable team.",
  },
  {
    title: "A Busy Summer Continues",
    post_date: "July 2026",
    image_src: "/images/blog-page/blog-post-images/2026/july/july-a.webp",
    image_alt: "",
    image_width: 456,
    image_height: 342,
    second_image_src: "/images/blog-page/blog-post-images/2026/july/july-b.webp",
    second_image_width: 456,
    second_image_height: 342,
    second_image_alt: "",
    text: [
      "July has gotten our summer off to a fast start! We were on the West Coast before heading to the upper Midwest, and St. Louis is certainly keeping us busy this time of year.",
      "It's such a privilege to tell stories that range from a truly special summer camp in Missouri to a revolutionary initiative at WashU. One particular project really puts things into perspective.",
      "We created a series of videos to help children prepare for Thyroid Cancer Treatments. This type of project is one of the big reasons that I started this company. As these patients and their families go through the hardest moments of their life, we're proud to be part of their journey even in a small way.",
    ],
    // video: {
    //   playback_id: "",
    //   title: "",
    //   image_src: "",
    // },
    closing_tag: "Wait until you hear what we're doing in August...",
    author: "Mike Martin",
    slug: "a-busy-summer-continues-july-2026",
    description: "A busy July takes MMM from the West Coast to the upper Midwest, with projects featuring Camp Rhythm, WashU, and videos about thyroid cancer treatments.",
  },
  {
    title: "Ten Years. One World Cup. Countless Memories.",
    post_date: "June 2026",
    image_src: "/images/blog-page/blog-post-images/2026/june/june-a.webp",
    image_alt: "Kevin and his friend Aaron at the 2026 FIFA World Cup in Seattle, WA.",
    image_width: 456,
    image_height: 342,
    second_image_src: "/images/blog-page/blog-post-images/2026/june/june-b.webp",
    second_image_width: 456,
    second_image_height: 342,
    second_image_alt: "Kevin enjoying the 2026 FIFA World Cup in Seattle, WA.",
    text: [
      "April 1, 2026 I celebrated my 10 year anniversary at Mike Martin Media. It's been an incredible journey. I count my blessings everyday that Mike Martin had confidence to bring me aboard in 2016. What an amazing ride it has been.",
      "Everyone at MMM has interests, hobbies, and passions outside of work. One of my biggest passions is soccer. I am a member of the St. Louligans, the largest supporter group of St. Louis CITY. You can find me at any home match helping run the Silly Tailgate at Schafly Beer before all the home matches.",
      "But my 1st soccer love will always be USA SOCCER, I bleed Red, White, and Blue. I love supporting everything about US Soccer, the USMNT, USWNT, and anything in between. I've been a longtime member of the American Outlaws.  The American Outlaws are the largest supporters group for the United States Men's and Women's National Soccer Teams. 200+ chapters, 30,000 members across the country.One voice. I am currently serving as the President of the American Outlaws St. Louis Chapter(AOSTL). We have an official chapter bar, Amsterdam Tavern, one of the best soccer bars in the country located in the Tower Grove South neighborhood. You can find AOSTL members watching all the US matches there.",
      "That brings us to the 2026 FIFA World Cup. Hosted by the USA, Canada, and Mexico. The watch parties at Amsterdam have been epic. The US opening match vs Paraguay had Morganford Ave closed for an outdoor watch party. The US won 4-1. The excitement was building for the next match. I was lucky enough to get tickets for that match, USA vs Australia match in Seattle, WA. This would be the 1st World Cup match I have attended in person. Needless to say I was super excited.",
      "My friend Aaron and I headed to Seattle on Wednesday evening, the match was scheduled for Friday at noon local time. After attending the Orioles-Mariners game on Thursday afternoon, it was time for the WC activities to begin. The American Outlaws have a tradition of hosting a Night before party before any US soccer match.Thursday evening we enjoyed hanging out with other AO members from across the country, the buzz around the city was building. Honestly, I couldn't sleep much that night, anticipating my 1st World Cup match. The next morning it was time for the AO tailgate at 8 am. It was unlike any other I had been to before, USA fans were ready. So much red, white, and blue. Of course I was decked out, USA bandana, our local AOSTL jersey, USA sunglasses and our AOSTL soccer scarves.",
      "Now it was gametime….we made our way to Lumen Field. We had gotten tickets through the American Outlaws lottery, all of us together in the 300 level of the stadium, our seats were in the 2nd to last row. None of that mattered, we were at our 1st WC match. The atmosphere was ELECTRIC! What happened next was totally unexpected. Our seats were upgraded, we couldn't believe it when we found out we would be sitting in the front row! LUCKY was an understatement.",
      "After the match, we partied the day and night away with the American Outlaws and fellow USA supporters, and what was even cooler was the Australian fans that partied with us. We all came together to celebrate the beautiful game of soccer. That was what I was looking forward to the most and it lived up to what I was hoping it would be. What an incredible 1st World Cup experience. #WhyNotUs has been the rallying cry for the USMNT this World Cup, I for one BELIEVE! GO U-S-A!",
    ],
    // video: {
    //   playback_id: "",
    //   title: "",
    //   image_src: "",
    // },
    closing_tag: "Until next time,",
    author: "Kevin Marshall",
    slug: "ten-years-one-world-cup-countless-memories",
    description: "Kevin reflects on his 10-year anniversary at Mike Martin Media and shares his experiences attending the 2026 FIFA World Cup, highlighting the excitement of supporting the U.S. Men's National Soccer Team and the camaraderie among fans.",
  },
  {
    title: "From Rehearsal to Gala",
    post_date: "May 2026",
    image_src: "/images/blog-page/blog-post-images/2026/may/may-a.webp",
    image_alt: "The St. Louis Children's Choirs performing on stage during their 2026 In Harmony Gala Celebration.",
    image_width: 456,
    image_height: 342,
    second_image_src: "/images/blog-page/blog-post-images/2026/may/may-b.webp",
    second_image_width: 456,
    second_image_height: 342,
    second_image_alt: "The St. Louis Children's Choirs performing on stage during their 2026 In Harmony Gala Celebration.",
    text: [
      "Earlier this spring, MMM had the opportunity to create the fundraising video for The St. Louis Children's Choirs' 2026 In Harmony Gala Celebration. On April 11, I attended the event and watched the piece come to life in the room it was made for.",
      "There's always something different about seeing a story play in front of a live audience, especially when it supports an organization doing meaningful work in the community. The energy in the room, the reactions from attendees, and the response following the video made it clear just how much people care about the impact The St. Louis Children's Choirs continues to have on young singers across our region.",
      "It was a privilege to have our team capture practices, dress rehearsals and performances over several months. This allowed us to tell the 'behind-the-scenes' story of the dedication and effort that goes into each event.",
      "We're grateful to have played a small role in helping share that story and support the evening's fundraising efforts. Nights like this are a reminder that video can do more than communicate information. When done well, it can help people connect, feel something, and take action.",
      "A huge thank you to The St. Louis Children's Choirs team for trusting us with such an important part of the evening.",
    ],
    // video: {
    //   playback_id: "",
    //   title: "",
    //   image_src: "",
    // },
    closing_tag: "Until next time,",
    author: "Mike Martin",
    slug: "from-rehearsal-to-gala",
    description: "CEO Mike Martin reflects on the experience of creating a fundraising video for The St. Louis Children's Choirs and seeing it come to life at their gala event.",
  },
  {
    title: "A Different Point of View",
    post_date: "April 2026",
    image_src: "/images/blog-page/blog-post-images/2026/april/april-a.webp",
    image_alt: "One of the MMM team members operating a drone on location at a train yard along the Illinois riverfront.",
    image_width: 456,
    image_height: 342,
    second_image_src: "/images/blog-page/blog-post-images/2026/april/april-b.webp",
    second_image_width: 456,
    second_image_height: 342,
    second_image_alt: "One of the MMM team members preparing a drone for takeoff on location at a train yard along the Illinois riverfront.",
    text: [
      "This past month, our team had the opportunity to capture drone footage on location along the Illinois riverfront during a barge shoot. Projects like this are always a reminder of how different every production can be and how much planning goes into getting the right shot safely and efficiently.",
      "From early setup to aerial coverage over the water, it was one of those shoots that pushed us into a unique environment and gave us the chance to capture visuals you do not see every day.",
      "We've also continued documenting more behind-the-scenes moments during productions so clients can get a better sense of what goes into the work before the final edit is delivered. Keep an eye out for more case studies and project breakdowns coming soon.",
    ],
    // video: {
    //   playback_id: "",
    //   title: "",
    //   image_src: "",
    // },
    closing_tag: "More to come,",
    author: "Clark Martin",
    slug: "different-point-of-view",
    description: "Clark shares insights from a recent drone shoot along the Illinois riverfront and teases upcoming behind-the-scenes content.",
  },
  {
    title: "March at MMM: What You Didn't See (But Will Soon)",
    post_date: "March 2026",
    image_src: "/images/blog-page/blog-post-images/2026/march/march.webp",
    image_alt: "A behind-the-scenes look at the MMM team during a production.",
    image_width: 456,
    image_height: 342,
    // second_image_src: "/images/blog-page/blog-post-images/.webp",
    // second_image_width: 456,
    // second_image_height: 342,
    // second_image_alt: "",
    text: [
      "The payoff for any video is the final, polished cut, which is typically the version you see.",
      "Lately, though, we've been putting more intention into capturing what happens along the way.",
      "Not just the shoot itself, but everything around it. The setup, the adjustments, the small decisions that quietly shape the end result. We think that's where a lot of the real story lives.",
      { type: "heading", content: "Why Behind-the-Scenes?" },
      "Even a straightforward shoot has more going on than most people ever see: Early call times, last-minute pivots, or small tweaks that end up making a big difference.",
      "We've always done this work but we just haven't shown much of it. We'd like to bring you inside our world. Not in a staged way, just a more honest look at what the process actually feels like.",
      { type: "heading", content: "What This Means for You" },
      "Our crew is what makes MMM so special and we want you to “meet” them so to speak. If you're considering working with us, this gives you a clearer sense of what to expect.",
      "The final video matters, but so does the experience of getting there.",
      { type: "heading", content: "What's Coming" },
      "Be on the look out for all new case studies we'll be sharing soon. They'll go deeper into the thinking behind each project and include more of the real moments from production. We are looking forward to working with you soon!",
    ],
    // video: {
    //   playback_id: "",
    //   title: "",
    //   image_src: "",
    // },
    closing_tag: "Until next time,",
    author: "Clark Martin",
    slug: "march-at-mmm",
    description: "",
  },
  {
    title: "Sandon's Introduction",
    post_date: "February 2026",
    image_src: "/images/blog-page/blog-post-images/2026/feb/february-a.webp",
    image_alt:
      "Sandon with a camera taking pictures of a guitarist performing on stage.",
    image_width: 456,
    image_height: 342,
    second_image_src:
      "/images/blog-page/blog-post-images/2026/feb/february-b.webp",
    second_image_width: 456,
    second_image_height: 342,
    second_image_alt: "Sandon working a photo shoot with other members of the MMM team.",
    text: [
      "Hi! I'm Sandon, and I'm fairly new to the MMM team, joining in August 2025. My previous job was as a video director for a large YouTube channel in St. Louis. During my time there, I got to do a bunch of crazy things. I filled bathtubs with slime, played hide-and-seek with my boss, and ate lots and lots of weird candies. The most valuable thing, however, was how much I learned about directing, lighting, and cinematography, which is my true passion. What I found myself longing for was the ability to use those skills to tell unique and meaningful stories. Enter Mike Martin Media.",
      "When I joined the team, it was immediately clear how much everyone at MMM cares about finding the story behind every shoot. Being surrounded by curious, talented creatives who value people as much as the final product is incredibly energizing. No two days look the same and getting to meet new people while helping turn their experiences into meaningful, compelling stories is what drives my love for video production. I'm excited to be part of a team that's always pushing to go above and beyond, and I can't wait to see what the future holds.",
    ],
    // video: {
    //   playback_id: "",
    //   title: "",
    //   image_src: "",
    // },
    closing_tag: "Until next time,",
    author: "Sandon Scott",
    slug: "introducing-sandon",
    description:
      "Sandon introduces himself and describes his early experiences at Mike Martin Media.",
  },
  {
    title: "Supporting Nonprofits Through Storytelling",
    post_date: "January 2026",
    image_src: "/images/blog-page/blog-post-images/2026/jan/jan-a.webp",
    image_alt: "Logo for Gratitude House, a sober-living home for women",
    image_width: 456,
    image_height: 342,
    // second_image_src: "/images/blog-page/blog-post-images/2026/",
    // second_image_width: 456,
    // second_image_height: 342,
    // second_image_alt: "",
    text: [
      "One of the most satisfying things we do at MMM is create fundraising and awareness videos for nonprofit organizations. In our 17 years as a company, we have had the privilege of working with dozens and dozens of nonprofits in the St. Louis area and around the country. These videos have helped raise millions of dollars for our nonprofit clients and that is why we do this work.",
      "I know how important these organizations are for our communities and the clients they serve. Gratitude House is just one example of essential life-saving work being done every day by nonprofit organizations. We are excited about our plans for working with nonprofits in 2026 and can't wait to share them with you and continue to play a vital role in helping those that need it the most.",
    ],
    video: {
      playback_id: "PRhLtcYJZFLOtXvt02gP45eolkvlty2QlUAKo4hdlfl4",
      title: "Gratitude House",
      image_src:
        "https://image.mux.com/PRhLtcYJZFLOtXvt02gP45eolkvlty2QlUAKo4hdlfl4/thumbnail.webp?width=576&height=324&time=42",
    },
    closing_tag: "Until next time,",
    author: "Mike Martin",
    slug: "supporting-nonprofits-through-storytelling",
    description:
      "A look at Mike Martin Media's ongoing work with nonprofit organizations and the impact of fundraising and awareness videos.",
  },
  {
    slug: "life-between-keyframes",
    title: "Life Between Keyframes",
    post_date: "November 2025",
    image_src: `${basePath}2025/2025-nov-a.webp`,
    image_width: 432,
    image_height: 342,
    image_alt: "The user interface of video editing software",
    second_image_src: `${basePath}2025/2025-nov-b.webp`,
    second_image_width: 432,
    second_image_height: 342,
    second_image_alt: "A graphic showing keyframes and motion paths.",
    text: [
      "At Mike Martin Media, as an editor, most of my days are spent inside Premiere and After Effects. Cutting, cleaning, compositing, and making things feel seamless. It is a lot of trial and error, a lot of long hours, and a lot of fixing problems that no one ever sees.",
      "Sometimes that means masking out peanut butter on someone's chin during an interview. Other times it's removing an outlet that snuck into a shot. It's the kind of detail no one ever notices, which is the goal.",
      "I am lucky to work with a team that trusts the process and keeps pushing the craft forward. We make it work, frame by frame.",
      "P.S. Here is a fully functional After Effects expression for Position that adds a realistic settle after your last keyframe. It uses sliders so you can dial it in fast.",
      `// Apply to Position
amp = effect("Amp")("Slider");      // 0.02 to 0.2 is common
freq = effect("Freq")("Slider");    // 2 to 5
decay = effect("Decay")("Slider");  // 3 to 7

n = 0;
if (numKeys > 0){
  n = nearestKey(time).index;
  if (key(n).time > time) n--;
}

if (n == 0){
  value
} else {
  t = time - key(n).time;
  v = velocityAtTime(key(n).time - thisComp.frameDuration/10);
  value + v*amp*Math.sin(freq*2*Math.PI*t)/Math.exp(decay*t)
}
      `,
      "What it does:",
      "After the final keyframe this adds a damped bounce based on the incoming velocity. Amp controls how far it overshoots, Freq controls how fast it oscillates, Decay controls how quickly it settles. If there are no keyframes it returns the base value. Create three Sliders on the same layer named Amp, Freq, and Decay, then paste this on Position. Works in 2D or 3D and respects your actual keyframed motion.",
    ],
    // vimeo_src: "",
    // video: {
    //   playback_id: "",
    //   title: "",
    //   image_src: "",
    // },
    closing_tag: "Until next time,",
    author: "Paul Baker",
    description:
      "Paul shares insights into the detailed work of video editing and provides a useful After Effects expression for adding realistic motion to animations.",
  },
  {
    title: "Next Stop: San Diego, Cameras Ready",
    post_date: "July 2025",
    image_src: "/images/blog-page/blog-post-images/2025/2025-july.webp",
    image_alt: "The MMM team prepares for a video shoot in front of a green screen.",
    image_width: 456,
    image_height: 342,
    // second_image_src: "",
    // second_image_width: 456,
    // second_image_height: 342,
    // second_image_alt: "",
    text: [
      "The last time I wrote a blog post, I spoke about how much I enjoy working at MMM, and after another year, I'm going to do it again.  I've had a lot of mishaps and bad luck recently, but the one thing that keeps me sane is my job!  I don't think a lot of people have the privilege of saying that, and I don't take it for granted.  I strive to learn and improve every day, even when things get extra busy.  If given the option of working from home in the comfort of my big warm robe, I would still choose to work in the office because it feels like where I belong.  Maybe I need to get a big warm robe for the office too!",
      "Soon I will be taking my first solo travel trip with MMM to sunny San Diego, which I have never been!  I'm excited to explore the city, maybe visit the beach, and film a sweet interview.  As a person with Celiac's disease, it's fun to try gluten free restaurants in new cities, so I will definitely be doing my research.  Can't forget to get sunscreen too!",
    ],
    closing_tag: "Stay tuned—sun, shoots, and SPF.",
    author: "Luke Bradshaw",
    slug: "next-stop-san-diego",
    description:
      "Luke shares his excitement about his upcoming solo travel trip to San Diego with Mike Martin Media, reflecting on his positive experiences at the company and his eagerness to explore a new city.",
  },
  {
    title: "The end of an era",
    post_date: "June 2025",
    image_src: "/images/blog-page/blog-post-images/2025/2025-june-a.webp",
    image_alt: "Zoë and the MMM team",
    image_width: 456,
    image_height: 342,
    second_image_src:
      "/images/blog-page/blog-post-images/2025/2025-june-b.webp",
    second_image_width: 456,
    second_image_height: 342,
    second_image_alt: "Zoë's office. How it started and how it's ending.",
    text: [
      "If I have not had the pleasure of meeting you yet, my name is Zoë. I started working at MMM the same day that we all moved into the new studio at 3333 in 2021. It kind of felt like everyone got a 'fresh start' at the same time. Me with the company, and everyone else with the new studio. That was four years ago now. So wow, how time flies!",
      "In that time, both the insides and the outsides of the company look a little different. People have come and gone, we've acquired new space and new gear, and our company behaviours and habits have also changed. I definitely relate to the studio in that way. I'm four years older, I've grown so much in my career and abilities, which means I've also embraced new challenges and met new obstacles.",
      "MMM has given me my first full-time job and an incredible introduction to the world of video production. I've learned more than I could have imagined. I made friends for a lifetime where I just expected to meet coworkers. I am definitely a different person than I was before MMM, and for the better. This incredible team of people has helped shape me into the filmmaker that I am today and I could not be more grateful for them. I am so sad to be leaving MMM after an amazing four years here, but the company will live without me (I don't know how but I am sure y'all will manage). I will never forget this company, the people it brought me, or the many lessons I've learned here. I hope y'all dont forget me either.",
      "Time changes everything, but I can tell that the heart and soul of MMM will forever be intact.",
    ],
    closing_tag: "MMM, weird but in a good way -- always.",
    author: "Zoë Calsyn",
    slug: "end-of-an-era",
    description:
      "Zoë reflects on her four years at Mike Martin Media and the changes she's seen in the company and herself as she prepares to move on to a new professional chapter.",
  },
  {
    title: "My MMM Family",
    post_date: "April 2025",
    image_src: "/images/blog-page/blog-post-images/2025/2025-april-a.webp",
    image_alt:
      "Adam, Kevin, and Mikey hanging out with the team mascot as they take in a ballgame.",
    image_width: 456,
    image_height: 342,
    second_image_src:
      "/images/blog-page/blog-post-images/2025/2025-april-b.webp",
    second_image_width: 456,
    second_image_height: 342,
    second_image_alt: "Adam and Zoë enjoying a beverage.",
    text: [
      "Working at MMM has been one of the most rewarding experiences of my career. From day one, I felt welcomed into a community that genuinely values support, camaraderie, and collaboration. The tight-knit, family-like atmosphere here has transformed my perspective on what a workplace can be. I quickly realized that my colleagues were more than just coworkers; they became friends. We share our professional experiences and personal stories, creating bonds that go beyond the office. This sense of belonging has made my job not just about work but about being part of something meaningful.",
      "Every colleague who has come and gone has contributed to the legacy of MMM. Our tight-knit culture continues to thrive as we welcome new faces and embrace the changes that come our way. I'm grateful for every individual who has been part of this journey, and I look forward to the future we're building together.",
    ],
    closing_tag: "Until next time,",
    author: "Adam Buchheit",
    slug: "my-mmm-family",
    description:
      "Adam reflects on the family-like atmosphere and the tight-night culture that makes working at MMM special.",
  },
  {
    slug: "learning-never-stops",
    title: "Learning Never Stops",
    post_date: "March 2025",
    image_src: `${basePath}2025/2025-mar.webp`,
    image_alt: "Remi at the job with the MMM team.",
    image_width: 456,
    image_height: 342,
    // second_image_src: "/images/blog-post-images/secondary/.webp",
    // second_image_width: 208,
    // second_image_height: 109,
    // second_image_alt: "",
    text: [
      "I share an inside joke with my best friend, who's a high school teacher: I'm a “forever student.” She often shares nuggets of wisdom with me (usually from her lesson plans), and every time, I'm reminded of just how much more there is to learn! This became even clearer when I stepped into my new role at MMM. It's easy to enter a new job with the mindset that you've got it all figured out—after all, you've got the resume to prove it. But I quickly realized how wrong that assumption was.",
      "Moving to a new city, working with new colleagues, and engaging with new clients has taught me so much already. It's not just about refining technical skills, but also about how to build and nurture client relationships and grow creatively.",
      "This month, we had the chance to visit Nashville, and our team put some of those lessons into practice. We shot a Tugboat event at the Country Music Hall of Fame, and I learned so much from my colleagues Tom and Kevin. Their approach to client relations and communication during the trip really made an impact.",
      "I'm beyond excited to continue learning and growing in this role—and I hope to inspire others to keep learning, too!",
    ],
    closing_tag: "Till next time,",
    author: "Remi Heckert",
    description:
      "Remi talks about the importance of learning and growth in her new role at Mike Martin Media.",
  },
  {
    slug: "growth-and-gratitude",
    title: "15 Years of Growth and Gratitude",
    post_date: "February 2025",
    image_src: `${basePath}2025/2025-feb.webp`,
    image_alt: "A young Tom with an old school video camera.",
    image_width: 456,
    image_height: 342,
    text: [
      "15 years ago, the first iPad was released, Instagram was launched, Tik-Tok was only a song by Kesha, and I started working at Mike Martin Media. While it seems like a long time to look back on, the journey itself feels like it's happened in the blink of an eye.",
      "I vividly remember becoming the first employee of MMM, and I was excited to start, although I had no idea what the future would have in store. Mike and I drove to every shoot, with the gear packed in the trunk, and gave every opportunity our hardest effort. Over time, we gathered more work, grew the team, bought more gear, and hustled just as hard. There were lots of late nights and stumbling blocks, but there were also a lot of laughs and great memories.",
      "Now, we have an entire team of talented professionals, an amazing studio, and a long list of clients that we are thrilled to work with. But what I think holds true, is that we all still put in that same hard effort day in and day out, just like we did 15 years ago. The true culture of MMM is knowing that we are lucky enough to be trusted to craft the messages for our trusted partners, and we have never taken that responsibility lightly.",
      "So, while reminiscing on my quindecennial (I had to look that up), I am thankful for the opportunity to have started my professional life here, but I’m just as thankful for everyone who has helped build us into the company we are today.",
    ],
    closing_tag: "Until next time,",
    author: "Tom Young",
    description: "Tom refelcts on 15 years of growth at Mike Martin Media.",
  },
  {
    slug: "starting-my-career",
    title: "Starting My Career At MMM",
    post_date: "January 2025",
    image_src: `${basePath}2025/2025-jan.webp`,
    image_alt: "Robert showing off his photographer credentials. ",
    image_width: 456,
    image_height: 342,
    text: [
      "2024 has been an incredible year of accomplishment for me. Not only did I get the chance to see my favorite band Sum 41 perform on their final tour together, and reconnect with a few of my best friends who I felt like I had drifted away from, but I also got hired at what is perhaps the coolest video production company in Saint Louis.",
      "With struggling to find the right level of employment after college, I was starting to wonder if there was anything here for me or if I had taken the wrong path - I started to lose faith in myself. But after choosing to take the last chance I had to go see Sum 41 and then have the lead singer Deryck Whibley point directly at me in the front of the crowd from onstage, I found hope. Around the same time I had landed an interview at a certain video production company in the city... The stars were aligning. For the first time in a long time I felt like I was right where I needed to be and that luck was on my side.",
      "Now, I'm a self-supportive adult with a proper job in my field that I truly enjoy!",
      "I've never worked for a video production company before, I've always worked by myself freelancing. So even though I'm not sure what it's normally like to work at a production company, I don't think I'll find another workplace that's just as comfortable, fun, and personable as the environment that the employees of MMM have created for themselves and their clients.",
      "I started in August 2024 and I've already done so much and been sent to so many new places. The most memorable experiences I've had so far include meeting world-famous olympians Ronnie Coleman and Eric Newby at Club Fitness, capturing Siteman Cancer Center's 10,000th stem cell transplant, and shooting behind the scenes of a brand new pharmaceutical research & development center for bioMérieux in Philadelphia. I would never have been able to meet these extraordinary individuals or attend these exclusive events without being given the opportunity to start a career with Mike Martin Media.",
      "I'm eternally grateful for my first official job in video production at a company that believes in me, trusts me, and supports me. Even though I only learned about this company a few months ago through a recruitment bot, I feel as though this is where I've always been heading. I'm looking forward to meeting and experiencing all the new people and places this amazing position will introduce me to in the coming new year.",
      "With enough time and effort (and a lil' bit of luck), hard work is well rewarded.",
      "",
    ],
    closing_tag: "Keep on trekking,",
    author: "Robert",
    description:
      "Robert reflects on his first few months on the job at Mike Martin Media.",
  },
  {
    slug: "year-end-review",
    title: "2024 Review",
    post_date: "December 2024",
    image_src: `${basePath}2024/2024-dec.png`,
    image_alt: "The MMM team at work in the studio using a green screen.",
    image_width: 456,
    image_height: 338,
    // second_image_src: "/images/blog-post-images/.png",
    // second_image_width: 208,
    // second_image_height: 109,
    // second_image_alt: "",
    text: [
      "We kicked off 2024 with high energy and a clear goal: to elevate our storytelling and push creative boundaries. From our dynamic production team to our cutting-edge studio space, this year has been all about creating content that leaves a lasting impact.",
      "As the year comes to a close, we at Mike Martin Media want to take a moment to reflect on what has been an exciting, productive, and incredibly creative 2024. It's been a year of big milestones, meaningful collaborations, and incredible projects. We've had the privilege of working with talented clients, expanding our creative horizons, and continuing to grow as a team. With over 80 out of town trips in more than half of the US and 5 different countries this year our crew has been busy, some just getting home from North Carolina and Nashville. We welcome them back into the office as we move towards the Holidays closing this year with team festivities and the celebration of our best year yet.",
    ],
    closing_tag: "Happy Holidays",
    author: "Clark Martin",
    description:
      "Clark reflects on the year that was 2024 at Mike Martin Media.",
  },
  {
    slug: "note-from-ceo",
    title: "A Note from the CEO",
    post_date: "November 2024",
    image_src: `${basePath}2024/2024-nov.png`,
    image_width: 456,
    image_height: 282,
    image_alt:
      "The MMM team. We work hard, play hard, and spend a lot of time laughing.",
    text: [
      "I started MMM in my basement in 2009 after a decade of working in television news. I discovered that there were so many stories that needed telling in St. Louis and around the world. Stories that would create positive impacts and help people achieve their goals. I wanted to make a difference.",
      "I was armed with a Mac Pro, Final Cut software, and one of the first affordable HD cameras that came to the market. I had one client, St. Patrick Center (who we still work with today)",
      "With the help of some amazing and talented people, MMM has grown and touched many lives over the last 15 years. Here are some stats that we're proud of:",
      "",
      "• MMM has donated over $320,000 in work to nonprofit organizations.",
      "• MMM has served over 1,500 clients.",
      "• MMM has completed over 4,700 projects.",
      "• MMM has captured video in 45 states and 7 countries.",

      "I have more equally impressive stats, but I'm not one to brag...  :)",
      "Fall is always busy for us, and 2024 is no different. I'm fortunate to have such a great team, and if you work with us you'll see why!",
    ],
    video_src:
      "https://player.vimeo.com/video/799944146?h=7ce1e106da&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    closing_tag: "Peace!",
    author: "Mike Martin",
    description:
      "Mike shares some thoughts on the growth and impact of Mike Martin Media over the past 15 years.",
  },
  {
    slug: "note-from-mary",
    title: "A Note from Mary",
    post_date: "October 2024",
    image_src: `${basePath}2024/2024-oct.png`,
    image_width: 456,
    image_height: 342,
    image_alt:
      "The MMM office decorated for the annual Music at the Intersection festival.",
    // second_image_src: "/images/blog-post-images/sept-2024-pic2.png",
    // second_image_width: 208,
    // second_image_height: 109,
    // second_image_alt: "The MMM team.",
    text: [
      "Now that September has come to a close, I have now officially been a part of the MMM family for a year! I could not be more grateful to be a part of such an amazing team.  One of the things I love about my job is that I'm often handed tasks that allow me to have some creative freedom.",
      "Every September, Music at the Intersection fills the streets around our office with vibrant live performances, food trucks, and vendors. It's one of our favorite annual events to capture content for. This year, I was tasked with painting a big, flashy sign for visitors to see from our window—and flashy it was!",
      "Mike and I put our creative brains together and decided on using glow-in-the-dark paint, so it would beam brightly out our window.  I had so much fun taking the sign home and splattering a rainbow of colors on it.  I can't really think of any other job that would allow me to do such a fun project!",
      "I can't emphasize enough how much I love working with a team of so many creative individuals.  I learn so much from each person as I work with them on different shoots. I think it's important to surround yourself with people who inspire you and support your strengths, and I truly feel that energy every day at MMM.",
    ],
    closing_tag: "Until next time,",
    author: "Mary Scott",
    description:
      "Mary talks about her first year at Mike Martin Media and the creative freedom she's been given. She describes the experience of painting a sign for the annual Music at the Intersection festival.",
  },
  {
    slug: "olympic-fever",
    title: "Olympic Fever",
    post_date: "September 2024",
    image_src: `${basePath}2024/2024-sept.png`,
    image_width: 456,
    image_height: 342,
    image_alt:
      "Rachel from MMM with Eric Newby, captain of the USA Wheelchair Rugby team",
    second_image_src: `${basePath}2024/2024-sept-pic2.png`,
    second_image_width: 208,
    second_image_height: 109,
    second_image_alt: "Rachel from MMM with Jackie Joyner-Kersee",
    text: [
      "I will never forget the first Olympian I met, Jackie Joyner-Kersee. She was incredibly kind and chatted with me as I told her how I wanted to be a track star when I grew up. That was in 2016. This year, I had the chance to meet and interview another Olympian, Eric Newby, captain of the USA Wheelchair Rugby team. Eric's story is pretty remarkable and I was so honored to be able to talk with him about his life, family, and of course, wheelchair rugby. ",
      "After we finished our interview and captured footage of him working out to prepare for the 2024 Paralympics in Paris, he let me hold one of his medals, a silver from the Tokyo games. Before the video shoot was over, I met his sweet little boy and we all took a photo. ",
      "Video production can take you all around the world and sometimes, you might meet some heroes, lifelong and new. Every new experience is a reminder that video production is exactly where I'm supposed to be; meeting some seemingly ordinary people who do extraordinary things. I don't get to be on-location as much as I used to when I first started producing, shooting and editing, but when I get the opportunity, I get excited all over again. Here's hoping USA Wheelchair Rugby brings home the Gold. ",
    ],
    vimeo_src:
      "https://player.vimeo.com/video/1001383081?badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
    video: {
      playback_id: "uAJfCDRMKASXG4wAjX5vSrSu4Qi8h2T2xlp5TzDY8uM",
      title: "Club Fitness Share to Inspire - Eric Newby",
      image_src:
        "https://image.mux.com/uAJfCDRMKASXG4wAjX5vSrSu4Qi8h2T2xlp5TzDY8uM/thumbnail.webp?width=576&height=324&time=52",
    },
    closing_tag: "Until next time,",
    author: "Rachel Lee",
    description:
      "Rachel shares her experiences meeting Olympians Jackie Joyner-Kersee and Eric Newby.",
  },
  {
    slug: "note-from-tom",
    title: "A Note from Tom",
    post_date: "July 2024",
    image_src: `${basePath}2024/2024-july.png`,
    image_width: 456,
    image_height: 326,
    image_alt: "A collage of images from Tom's trip to Germany and France",
    text: [
      "Travel is in MMM's DNA, and this month Mike and I were able to add two new countries to the list: Germany and France. We are fortunate to have the trust of our clients that allows us to explore the globe, and we are grateful for the opportunity.",
      "When it was time for work, we loved touring our client's amazing factory in Neckartenzlingen, and hosted a livestream out of their state-of-the-art facility. It's an honor to be a trusted partner delivering messaging to their global workforce.",
      "But after the event ended, we weren't quite ready to head back State-side. As an avid cyclist, I had been glued to the Tour de France that was currently underway. It took very little convincing to get Mike onboard with a quick stop over to Dijon, France to catch Stage 6 of the tour. It was an experience I'll never forget, and I'm so appreciative to work in a company that has a default attitude of: “yes, let's go for it!”",
      "I felt the trip fully embodied who we are as an organization. We explore, collaborate, and energize one another.  Every day is a new adventure, and we're always eager to go.",
    ],
    closing_tag: "Until next time,",
    author: "Tom Young",
    description:
      "Tom shares his experiences traveling to Germany and France for work and pleasure.",
  },
  {
    slug: "note-from-luke",
    title: "A Note from Luke",
    post_date: "June 2024",
    image_src: `${basePath}2024/2024-june.png`,
    image_width: 456,
    image_height: 344,
    image_alt: "Luke and some coworkers around a campfire on an MMM work trip",
    text: [
      "Hey everyone, it's Luke! I'm an editor and videographer with MMM, and I'm proud to be here every day.  When I wake up in the morning, I find myself excited to walk into the office to see my favorite coworkers and tackle whatever is on my plate that day. Personally, I find work can sometimes be a meditative experience. Sure, sometimes the project can be difficult, emotional, or long. But once the project is finished and approved, it's hard not to feel a sense of accomplishment and growth.",
      "Now that I'm done sapping about my job, let's talk about when we get to experience spending time with our coworkers outside of work! Twice a year, sometimes more, we plan a camping or float trip to get the whole office to come outside, smell the grass, and get to know each other outside of the screens and rolling chairs. We get to see who can build a fire, who can canoe without tipping, and who can design the most luxurious camping space. It's an opportunity to show your true colors and separate from the work mindset. The only time I've sang karaoke was at a work camping trip!",
      "My favorite memories have been the simple hardships we overcame as a group. Whether it be 30mph winds or 6 hours of straight downpour, we still find a way to have fun and enjoy ourselves! I'm thankful for the sense of family we've created in the office, and I'm thankful for the opportunities we are given to express ourselves within the group. I'm looking forward to our next trip and the many many inside jokes we'll come back with!",
    ],
    closing_tag: "Until next time,",
    author: "Luke Bradshaw",
    description:
      "Luke shares his experiences working at Mike Martin Media and the fun he had with his coworkers on a camping trip.",
  },
  {
    slug: "dayton-ohio-adventure",
    title: "Dayton, Ohio Adventure - From Video Shoots to Bar Arcades",
    post_date: "May 2024",
    image_src: `${basePath}2024/2024-may.png`,
    image_width: 456,
    image_height: 342,
    image_alt:
      "Welcome to Ohio sign on a bridge overpass viewed from the dashboard of a car",
    text: [
      "Hello and thank you for reading my blogpost! I'm Phillip, a passionate videographer and editor with Mike Martin Media. I recently embarked on a memorable work trip to Dayton, Ohio. Dayton greeted us with open arms. Although the weather was bitter cold, the welcome from our client and the town was warm. This wasn't just a business trip; it was the beginning of a story waiting to be told through our lenses.",
      "Our client's vision for corporate videos aimed at recruitment came to life over a focused three-day shoot. They shared their insights, enhancing the promotional pieces we crafted. This collaborative spirit affirmed that impactful video storytelling is as much about the message as it is about the medium.",
      "Dayton's bar arcades were a nostalgic playground where I unwound each night. Stepping into the vibrant buzz of arcade machines, I was instantly transported back to the carefree days of my youth. The mix of classic games and the social atmosphere provided the perfect counterbalance to the focus required for video editing services during the day.",
      "Having the chance to edit the videos we shot in Dayton was an honor that deepened my connection to the project. Often, the task of video editing services is passed to other team members, but this time, I was the storyteller piecing together the narrative. This role allowed me to immerse myself fully in the material, ensuring that each frame, transition, and audio cue conveyed the desired emotion and message.",
      "The pinnacle of any project is the moment you reveal the final product to the client. This project was no different. After intensive days of shooting, followed by meticulous video editing, the satisfaction of the client was paramount. Their response to our video production services was more than just an approval; it was an affirmation of the hard work and passion invested into their promotional videos",
      "It's these successful outcomes that drive our commitment to excellence in every aspect of our video marketing services.",
    ],
    closing_tag: "Until next time,",
    author: "Phillip Person",
    description:
      "Phillip shares his experiences on a work trip to Dayton, Ohio. He talks about the video shoots, the Dayton arcades, and the video editing process.",
  },
  {
    slug: "out-and-about-2024",
    title: "Out and About in 2024",
    post_date: "April 2024",
    image_src: `${basePath}2024/2024-april.png`,
    image_width: 456,
    image_height: 362,
    image_alt: "A collage of images from the MMM team's adventures in 2024",
    text: [
      "We're only about four months into 2024, but the MMM team has been keeping busy during the short timeframe.  Our travels have taken us all over the US map, from California to New York and everywhere in between.  We even took a few trips just outside of our borders to Canada and Mexico.  The MMMileage will not be stopping anytime soon! This year we are looking forward to potential adventures in Germany and India. More to come on those endeavors later this year!",
      "More recently, the team took the opportunity to gather around outside to catch the eclipse on April 8th.  Some of us were even adventurous enough to climb up to the rooftop to get a better look of the dimming sky.  Although the view from St. Louis was not full 100% coverage of the sun, it was still a pretty spectacular 99.1% view.  It was also a great excuse for us to go outside and eat barbeque.  A big shout out to our videographer Adam for cooking up some stellar burgers.",
      "Amongst other MMM shenanigans, the team has been participating in an internal sticker competition! With the arrival of some new St. Louis themed MMM stickers, the team has been challenged to place them all around the public (in acceptable locations of course).  If you spot any in the wild, let us know!",
    ],
    closing_tag: "Until next time,",
    author: "Mary Scott",
    description:
      "Mary shares the MMM team's adventures in 2024, including trips around the US, the eclipse, and the internal sticker competition.",
  },
  {
    slug: "inside-mmm-arizona-trip",
    title: "Inside MMM's Arizona Trip",
    post_date: "March 2023",
    image_src: `${basePath}2023/2023-mar.png`,
    image_width: 456,
    image_height: 342,
    image_alt:
      "The MMM team in action at the leadership conference in Phoenix, Arizona",
    text: [
      "Spring is one of MMM's busiest times of the year, perhaps even the busiest. This month has certainly been no exception. Last week we had a team fly out to Arizona for a 3-day conference, and today we touched down in China — more on that later.",
      "The leadership conference that our team captured in Phoenix provided the perfect example of the full service events we can cover, including everything from photography to live-streaming. Whether the objective was honoring award winners or recording day-long sessions, we were able to meet changing requests with ease.",
      "The leadership conference that our team captured in Phoenix is a perfect example of the full-service video support we offer for events, including everything from photography to live-streaming. Conferences are all-encompassing and we specialize in creating the pre-produced content, capturing day-long sessions, and anything else in between. Whether the objective was honoring award winners or gathering footage for future projects, we are always able to meet changing requests with ease.",
      "Four days spent across the country flew by fast with this team. Mikey, Tom, and Zoë, thank you for your time and talents! Check out some highlights from our trip on Instagram and Facebook and we'll see you on our next trips. Kentucky, Massachusetts, Texas, and Georgia, we're ready for you!",
    ],
    closing_tag: "Until next time,",
    author: "MMM",
    description:
      "The MMM team travels to Phoenix, Arizona for a leadership conference.",
  },
  {
    slug: "reflecting-on-the-season",
    title: "Reflecting on the Season",
    post_date: "January 2023",
    image_src: `${basePath}2023/2023-jan.png`,
    image_width: 456,
    image_height: 342,
    image_alt: "The MMM team playing Mario Kart at their annual tournament",
    text: [
      "It's that time of year again, that beautiful, special time of year when we all gather around to celebrate what truly matters: Mario Kart.",
      "The 2nd Annual MMM Mario Kart $100 Confrontation went DOWN earlier this month! After last year's close finish, this year's Confrontation was highly anticipated and extremely competitive. With twice as many races and racers as last year, tensions were high. The skill level of competitors ranged from total newbies to seasoned veterans, making for a truly entertaining event.",
      "Who won, you ask? Before someone won the 2nd Annual MMM Mario Kart $100 Confrontation, we all won one of our very own MMM awards. Throughout the past two years or so, various MMM employees have been bestowed a range of awards. Mike took time this year to give everyone an award, fit just for them. Awards ranged from “Social Influencer of the Year” for our social media manager, and “Longest Commute to Work of 2022  Award” to our newest addition, Ian Ramprashad, before he moved to St. Louis. Thank you Mike, for making sure we all are recognized and appreciated.",
      "This year's confrontation started off strong, with twelve total racers. But in the end, there could only be one winner.. Some stand out games included Josh vs. Rachel (she claims to be helpless but she absolutely held her own), as well as Nicole vs. Tom — the reigning champ versus Rachel's wife. “She's great, but usually on Nintendo 64” Rachel said of Nicole. Tom didn't hold back, but Nicole managed to pull out a win. Tom won that round but Nicole qualified for a position in Round 3. In Round 2 we saw Adam and Zoë face off in a heated and very close race that ended up going to Adam — before he had to leave for the night, reallocating his MMMario Kart Confrontation ranking to the loser of the race after his. No mercy for Zoë. Somehow the races of Josh vs. Paul were some of the most intense races of the night! Paul pulled ahead, giving Josh what was Adam's position.",
      "Round 3 was between Josh vs. Tom and Nicole vs. Paul. In a desperate fight to the finish, Round 4 was left to the two domineering players of the day, Tom and Paul.  The Final Confrontation was the most intense tournament of the night despite the dwindling number of attendees. Every move mattered, every trick and turn could make or break the racer's race. Lo and behold, the MMMember that claimed the first place prize this year was Tom Young, for the second year in a row! The $100 advertised for this Confrontation was divided into $75 for first place (Tom) and $25 for second place (Paul).",
      "We are so grateful to all of our talented participants for making this year another smashing success.",
      "Who will win next year's Confrontation? Will Tom be dethroned? When is this event usually held???",
    ],
    closing_tag: "Stay tuned to find out!",
    author: "MMM",
    description: "The MMM team reflects on their annual Mario Kart tournament.",
  },
  {
    slug: "six-months-down-six-more-to-go",
    title: "Six Months Down, Six More to Go!",
    post_date: "June 2022",
    image_src: `${basePath}2022/2022-june.png`,
    image_width: 456,
    image_height: 342,
    image_alt: "The MMM team team relaxing on a work trip",
    text: [
      "Can you believe it? We're already halfway through the year! As we reflect on the past six months and look forward to the next six, there's one thing for certain — we are busy. From constructing sets for in-house filming, to recording and producing two podcast series, to our usual — flying all over the country to meet any and all of your video production needs.",
      "Since our last post, we've packed in another handful of trips and fun projects.  Back in March, Rachel got to experience her first travel trip with Mikey and Dave to Indianapolis while Kevin and Adam filmed in Minneapolis. In April, Mikey, Tom, and Zoë enjoyed conducting a livestream recording in Chicago the same week that Kevin and Mike were in DC for a separate livestream! And the travel doesn't stop there… we have a crew in Chattanooga and New York this week, we are sending off another team to Nashville next week, and a team in Santa Clara at the end of the month.",
      "Additionally, there's no shortage of exciting events to cover in our own town of St. Louis. We are honored to have partnered with one of our clients to cover the NASCAR Enjoy Illinois 300 race that took place at World Wide Technology Raceway in early June. From the Driver Salute to the race on Sunday, it was a great event to be a part of!",
      "We would tell you some of the other fun projects we have lined up this year but, then what fun would that be? Follow our Facebook, Instagram and LinkedIn to stay up to date on all things MMM. We're @mikemartinmedia everywhere, and follow the #mmmgood hashtag! Post with #mmmgood when we film together and we'll repost your pic.",
    ],
    closing_tag: "Until next time,",
    author: "MMM",
    description:
      "The MMM team reflects on the first six months of 2022 and looks forward to the next six.",
  },
  {
    slug: "letter-from-kevin",
    title: "A Letter from Kevin",
    post_date: "April 2022",
    image_src: `${basePath}2022/2022-april.png`,
    image_width: 456,
    image_height: 342,
    image_alt:
      "a selfie of Kevin in front of a city skyline on a road trip for MMM",
    text: [
      "I'm lucky. I'm lucky to have an amazing daughter who is in her junior year at Murray State. I'm lucky to have an amazing job at Mike Martin Media. I'm lucky to have a job where I wake up every day and love going to work. I'm lucky to get to travel all over the country as part of that job. I mean we even have a hashtag we use, #MMMgood.",
      "My work trips with Mike Martin Media come with a lot of perks. MMM client trips have taken me to cities I have been to, cities I have never been to, and cities I have always wanted to go to. Some of the best trips are when they are close to my hometown of Hagerstown, Maryland, because I can meet up with my parents for lunch or dinner after work is done.",
      "I usually have some free time in the cities I visit and I love immersing myself in the local culture of a city. One rule I have on the road is to only visit local places. I love starting at a local brewery, talking to the home-towners, getting advice on where to eat, where to visit, and any hidden gems that I might need to see.  People are always more than willing to help me out.",
      "I really enjoy drinking local beer and eating at local restaurants. I love searching for what food a local city is known for and finding the best local spot to have that food. Ever had a “juicy lucy”, invented in Minneapolis? Do you love comparing the best crab cake places in Baltimore, MD like me? Hint, my favorite is Faidley's Seafood.",
      "This country has some pretty amazing breweries and restaurants that I would have never been to, if not for my MMM work travel. One example is Tulsa, Oklahoma. Not sure it would have been on my radar before but work from several of our clients has sent me there close to 20 times. Tulsa has an outstanding beer and food scene! I highly recommend it if you haven't been before.",
      "This country also has some beautiful destinations. I love finding unique and quirky places to check out in the cities I'm visiting. How can you pass up The American Gothic Museum in Eldon, Iowa, the Ft. Worth Water Gardens, the Google Emoji playground in Palo Alto, CA, the 60 ft “Driller” statue in Tulsa, the Santa Monica pier, which is the end of Route 66, and the stunning views of coastlines up and down the East and West Coast? I love capturing my visits to those places with selfies of myself and co-workers who are on the trips with me. Of course, even have a hashtag for those, #KevinSelfies.",
      "I'll be documenting my trips on social media so feel free to follow along on my MMM adventures:",
      "Facebook: www.facebook.com/kevin.marshall.7524",
      "Instagram: @kevinusmarshall",
      "Twitter: @kevinUSmarshall",
      "I'm lucky.",
    ],
    closing_tag: "Until next time,",
    author: "Kevin",
    description:
      "Kevin expresses his gratitude for his job at Mike Martin Media and shares his experiences traveling for work.",
  },
  {
    slug: "note-from-rachel",
    title: "A Note from Rachel",
    post_date: "February 2023",
    image_src: `${basePath}2022/2022-march.png`,
    image_width: 456,
    image_height: 342,
    image_alt:
      "Rachel from MMM in front of a camera interviewing a client during a video shoot",
    text: [
      "For years, I had the pleasure of working with MMM as a client and when I made the move to being a producer on the team, it felt like I had come home.",
      "Small businesses are so integral in every workforce sector and I'm so proud of the work we do for corporations, non-profits, and educational and medical institutions around the world. The work is fast-paced and we are so nimble and able to pivot at a moment's notice. This is rare and something our clients love.",
      "My favorite part of working at MMM is interviewing. I have always loved talking to people and now I get paid to do it, how cool! We are able to really get to the heart of a story and share all the wonderful things everyday people are doing or overcoming. I am consistently blown away at our team's photography skills, or motion graphics editing and our kick-ass video production.",
      "I knew video production was going to be in my life when I took my first high school media class and I consider it a true blessing that I'm able to do it every day. I am passionate about storytelling and everyone at MMM does it with intention, clarity and quality.  This is such a special place and I feel privileged to be on the team.",
    ],
    closing_tag: "",
    author: "Rachel",
    description:
      "Rachel talks about the evolution of her relationship with Mike Martin Media, as a client and part of the team.",
  },
  {
    slug: "note-from-mike",
    title: "A Note from Mike",
    post_date: "February 2022",
    image_src: `${basePath}2022/2022-feb.png`,
    image_width: 456,
    image_height: 304,
    image_alt:
      "Mike Martin and some of the MMM team taking a break during a video shoot",
    text: [
      "MMM is in full swing to start 2022!  Local shoots in St. Louis, Zoom recordings, Live Stream events and shoots from Texas to Nevada have highlighted the start to our year. We are booked for shoots from coast to coast over the next couple of months and we are looking forward to sharing our journey with all of you.",
      "Our new Midtown studio has proven to be a huge benefit for our local clients. This week, we are shooting a podcast in our brand new podcast studio. If you haven't been here yet, just reach out and we'll set up a time for a tour and grab you some lunch at one of our neighborhood favorites!",
      "Our team continues to grow, and we look forward to producing awesome content for our clients this year. We're happy to hop on a call or virtual meeting to help you with your next video project, so don't hesitate to reach out for a free consultation. Let us help you reach your goals in 2022!",
    ],
    closing_tag: "Until next time,",
    author: "Mike Martin",
    description:
      "Mike shares some thoughts on the start of 2022 at Mike Martin Media.",
  },
];
